### ISSUE TITLE
To the author

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [TimRivoli/Stock-Price-Trade-Analyzer#1]
What is your honest review? Is it a playground for understanding machinelearning or could it actually become a useful tool for stock prediction?

**Comment by TimRivoli** [comment]
It has taught me that historical average returns on index balanced
investments average about 8% through thick and thin.  Major crashes are
soon recovered from pulling you right back into that line after a few
years.  So, until we can come up with a model that does better than that
there is no point in deviating much from buy and hold on quality stocks.  I
haven't found a model yet, but most of my work has gone into making the
framework.  It has been a fun project and it takes the guess work out of
analyzing performance.  If I get a good idea then I can plug it in and test
it out without much effort.  I am currently working on an actor critic
robotic trader and a supervised learning trader.  I will post that as a new
project with the results.  No idea what they will be yet.
