### ISSUE TITLE
Latest Version of Pandas does not Support empty labels

### ISSUE THREAD

**Issue by orionnelson** [TimRivoli/Stock-Price-Trade-Analyzer#2]
KeyError: 'Passing list-likes to .loc or [] with any missing labels is no longer supported, see https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike'

**Comment by TimRivoli** [comment]
Where are you seeing that?  I have tracked a few of those down in the past and am not seeing in on my installation. I'm running Python 3.6.4 with Pandas 0.25.1

**Comment by orionnelson** [comment]
Sorry about that downgraded to 0.25.1 and things are working smoothly. Only other problem is with matplotlib however Im running python 3.8 so some issues are to be expected.

**Comment by TimRivoli** [comment]
I've fixed the matplotlib issue.  I had neglected to calculated the fields I was plotting.  Sloppy.  Sorry.
