### ISSUE TITLE
Why does it calculate for yesterday only?

### ISSUE THREAD

**Issue by charifbahloul** [TimRivoli/Stock-Price-Trade-Analyzer#5]
Loading ^SPX
Calculating stats ^SPX
Graphing ^SPX 2021-02-11
 Saved to data/charts/^SPX_0090d.png

**Comment by TimRivoli** [comment]
Could you please be more specific in what you are trying to do?

**Comment by charifbahloul** [comment]
Running Evaluate Prices.py. The first section of it.

**Comment by TimRivoli** [comment]
For 90 days on SPX, that must be the default options for DownloadAndGraphStocks(IndexList).  I get a full 90 days plus 15 days predicted foreword.  You don't see any of that?  Does your data\historical\^SPX.csv have data in it?  If not then maybe the data download failed.  Have you tried running it more than once?

**Comment by charifbahloul** [comment]
Today when I run it, it say that. But if I run it on a weekday after-hours, it says the day before.

**Comment by TimRivoli** [comment]
The data source is only pulling historical data, not today's data, so it only shows data of the latest closed date.
